// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://rqntfimwkalnthttngpy.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InJxbnRmaW13a2FsbnRodHRuZ3B5Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDUyODE1NDgsImV4cCI6MjA2MDg1NzU0OH0.3yQHElic0S6fpljn_KYw8XbSIjBit83IYnItVou33sY";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);